## Funckje

Funkcje w kontekście sieci neuronowych:
1. Matematyka:
    * `f_1(x) = x^2`
    * `f_2(x) = max(x, 0)`
    

2. Diagramy

3. Kod 

In [1]:
import numpy as np

In [4]:
# Operacje na listach pythona
a = [1,2,3]
b = [4,5,6]
a,b

([1, 2, 3], [4, 5, 6])

In [6]:
# Dodawanie dwóch tablic do siebie przy pomocy składni pythona
a + b

[1, 2, 3, 4, 5, 6]

In [7]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
# Operacja `a*b` na listach Pythona nie ma sensu

# Przykład użycia klasy ndarray z pomocą biblioteki NumPy 
a = np.array([1,2,3])
b = np.array([4,5,6])

a,b


(array([1, 2, 3]), array([4, 5, 6]))

In [9]:
# Opracja sumy na tablicach stowrzonych za pomocą funkcji array 
a + b

""" 
a = [1,2,3]
b = [4,5,6]

a + b ---> a[0] + b[0] + ... = (a+b)
"""

array([5, 7, 9])

In [10]:
a * b
""" 
a = [1,2,3]
b = [4,5,6]

a + b ---> a[0] * b[0] * ... = (a+b)
"""

array([ 4, 10, 18])

### W bibliotece 