# Vectors in python with Numpy lib

In [2]:
# Importing numpy
import numpy as np

# Checking numpy version
np.__version__

'1.24.3'

## Creation of a Vector in Python
**Syntax --> numpy.array(list)**

### Example 1: *Horizontal Vecotr*

In [5]:
test_data_list = [1, 2, 3, 4, 5]

In [7]:
vector = np.array(test_data_list)
vector = np.array(test_data_list)

In [12]:
print(f"Vector created from a list: {vector}\n")
print(f"Example: \n\t List -> {test_data_list} \n\t Vector -> {vector}")

Vector created from a list: [1 2 3 4 5]

Example: 
	 List -> [1, 2, 3, 4, 5] 
	 Vector -> [1 2 3 4 5]


### Example 2: *Vertical Vector*

In [13]:
test_data_list_2 = [
    [2],
    [4],
    [6],
    [10]
]
test_data_list

[1, 2, 3, 4, 5]

In [14]:
vector_2 = np.array(test_data_list_2)
vector_2 = np.array(test_data_list_2)

In [18]:
print(f"Vector created from a list2: {vector_2}\n")

print(f"Example: \n\t List -> {test_data_list_2} \n\t Vector -> {vector_2}")

Vector created from a list2: [[ 2]
 [ 4]
 [ 6]
 [10]]

Example: 
	 List -> [[2], [4], [6], [10]] 
	 Vector -> [[ 2]
 [ 4]
 [ 6]
 [10]]


# Basic Operations on a Python Vector

## 1. Performing addition operation on a Python Vector 
**Syntax: vector + vector**

In [19]:
test_data_list_1 = [10, 20, 30, 40, 50]
test_data_list_2 = [1, 2, 3, 4, 5]

In [21]:
vec1 = np.array(test_data_list_1)
vec2 = np.array(test_data_list_2)

In [22]:
print(f"Vector created from a list 1: {vec1}")
print(f"Vector created from a list 2: {vec2}") 

Vector created from a list 1: [10 20 30 40 50]
Vector created from a list 2: [1 2 3 4 5]


In [23]:
vec_add = vec1 + vec2 

In [25]:
print(f"Addition of two vectors: {vec_add}")

Addition of two vectors: [11 22 33 44 55]


## 2. Performing Subtraction of two vectors
**Syntax --> vector - vector**

In [26]:
test_data_list_1 = [10, 20, 30, 40, 50]
test_data_list_2 = [1, 2, 3, 4, 5]

In [27]:
vec1 = np.array(test_data_list_1)
vec2 = np.array(test_data_list_2)

In [28]:
print(f"Vector created from a list 1: {vec1}")
print(f"Vector created from a list 2: {vec2}") 

Vector created from a list 1: [10 20 30 40 50]
Vector created from a list 2: [1 2 3 4 5]


In [35]:
vec_sub = vec1 - vec2 

In [36]:
print(f"Subtraction of two vectors: {vec_sub}")

Subtraction of two vectors: [ 9 18 27 36 45]


## 3. Performing multiplication of two vectors
**Syntax --> vector * vector**

***Vector multiplication*** multiplies the elements of vector 1 by the elements of vector 2, and the product vector has the same length as the multiplication vector.

Let's visualize the multiplication operation:

x = [10,20] and y = [1,2] are two vectors. So the product vector would be v[ ],

***v[0] = x[0] * y[0]***

***v[1] = x[1] * y[1]***

In [37]:
test_data_list_1 = [10, 20, 30, 40, 50]
test_data_list_2 = [1, 2, 3, 4, 5]

In [38]:
vec1 = np.array(test_data_list_1)
vec2 = np.array(test_data_list_2)


In [39]:
vec1, vec2

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [44]:
vec_mul = vec1 * vec2 

In [45]:
vec_mul

array([ 10,  40,  90, 160, 250])

## 4. Performing Vector division operation
**Syntax --> vector/vector**

***In vector division.*** The resulting vector is the quotient values ​​after performing a division operation on the two vectors.

For better understanding, consider the following example. 

x = [10,20] and y = [1,2] are two vectors. So the resultant vector v would be,

**v[0] = x[0] / y[0]**

**v[1] = x[1] / y[1]**

In [47]:
test_data_list_1 = [10, 20, 30, 40, 50]
test_data_list_2 = [10, 20, 30, 40, 50]

test_data_list_1, test_data_list_2

([10, 20, 30, 40, 50], [10, 20, 30, 40, 50])

In [49]:
vec1 = np.array(test_data_list_1)
vec2 = np.array(test_data_list_2)

vec1, vec2

(array([10, 20, 30, 40, 50]), array([10, 20, 30, 40, 50]))

In [51]:
vec_div = vec1 / vec2

vec_div

array([1., 1., 1., 1., 1.])

## 5. Vector Dot Product
**Syntax --> vector1.dot(vector2)**

The vector dot product sums element-wise the products of two vectors. 

**vector c = x . y = (x1 * y1 + x2 * y2)**, 

it means that if we have one vector called *vec1* with params [x,y] and vector two called *vec2* with params [a,b] 

by using ***.dot*** function we recive equasion like this: *( x * a ) + ( y * b )*


**Example:** 

**[1]** *vec1 = np.array([10,20]), vec2 = np.array([2,3])*

**[2]** *result = vec1.dot(vec2)*

*result steps:*
* 10*2 
* 20*3 
* 20+60 
* 80 


In [72]:
# Test above example
vec1 = np.array([10,20])
vec2 = np.array([2, 3])
result = vec1.dot(vec2)
result

80

##### More examples

In [62]:
test_data_list_1 = [10,20,30,40,50] 
test_data_list_2 = [1,1,1,1,1]

test_data_list_1, test_data_list_2

([10, 20, 30, 40, 50], [1, 1, 1, 1, 1])

In [60]:
vec1 = np.array(test_data_list_1)
vec2 = np.array(test_data_list_2)

vec1, vec2

(array([10, 20, 30, 40, 50]), array([2, 1, 1, 1, 1]))

In [61]:
vec_dot = vec1.dot(vec2)

vec_dot

160

In [58]:
# Check if summation its true
sum1 = sum(test_data_list_1)
sum2 = sum(test_data_list_2)

sum1, sum2

(150, 5)